version: '3.4'

services:
  reportdb:
    image: mongo

  contactdb:
    image: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4  

  portainer:
    image: portainer/portainer-ce

  #contact.api:
  #  image: ${DOCKER_REGISTRY-}contactapi
  #  build:
  #    context: .
  #    dockerfile: src/Services/Contact/Contact.API/Dockerfile

  #report.api:
  #  image: ${DOCKER_REGISTRY-}reportapi
  #  build:
  #    context: .
  #    dockerfile: src/Services/Report/Report.API/Dockerfile

  #contact.grpc:
  #  image: ${DOCKER_REGISTRY-}contactgrpc
  #  build:
  #    context: .
  #    dockerfile: src/Services/Contact/Contact.Grpc/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
