version: '3.4'

services:
  reportdb:
    container_name: reportdb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  contactdb:
    container_name: contactdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ContactDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15680:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@shopping.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5052:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  #contact.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "DatabaseSettings:ConnectionString=Server=contactdb;Port=5433;Database=ContactDb;User Id=admin;Password=admin1234;"
  #  depends_on:
  #    - contactdb
  #  ports:
  #    - "8001:80"

  #report.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #    - "DatabaseSettings:ConnectionString=mongodb://reportdb:27018"
  #  depends_on:
  #    - reportdb
  #    - rabbitmq
  #  ports:
  #    - "8002:80"
  #    - "8003:443"
  #  volumes:
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  #contact.grpc:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #  ports:
  #    - "80"
  #    - "443"
  #  volumes:
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
